### ISSUE TITLE
Queries about the geom_psd function?

### ISSUE THREAD

**Issue by vignesh-mohan388** [tianshu129/foqat#113]
Hello Tianshu
I would like to ask you some doubts about the geom_psd fucntion? I have a data it contains 46 size bins. when I am trying to plot using geom_psd function, the graph is not displaying properly for my data but, i tried with your data it is working fine. so i would like to have your suggestion. kindly find the attached sample graphs (link) for further details. 
![sample graph](https://github.com/tianshu129/foqat/assets/79076215/b82ee294-9464-438d-b59f-588cc5a90036)

**Comment by tianshu129** [comment]
Hello Vignesh, because the y-axis defaults to a logarithmic scale, if there are fewer bins and a smaller particle size range, this situation (with a lot of blank space) might occur. You can try increasing the 'colsz' parameter. Another method is to interpolate the bins, which allows you to decrease the 'colsz', making the color transition in the graph more natural.

**Comment by vignesh-mohan388** [comment]
Hello Tianshu,

Thank you for your email. The issue got resolved and due to some work I
wouldn't be able to reply to you sorry for that. Have a good day.



*With thanks and warm regards,*
*VIGNESH Mohan,*
*Research Scholar,*
*Delhi Technological University.*
*Delhi-110042.*

**Comment by tianshu129** [comment]
Hi Vignesh,


It is OK. How do you know this package?


Best,


Tianshu
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/1/2023 13:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [tianshu129/foqat] Queries about the geom_psd function? (Issue #113) |

Hello Tianshu,

Thank you for your email. The issue got resolved and due to some work I
wouldn't be able to reply to you sorry for that. Have a good day.



*With thanks and warm regards,*
*VIGNESH Mohan,*
*Research Scholar,*
*Delhi Technological University.*
*Delhi-110042.*

**Comment by vignesh-mohan388** [comment]
Actually I need to plot size distribution graphs in R studio. While I was
searching related to this I got your package. It is really a good package.
I would like to explore more about this package as of now I have explored
only a few functions.



*With thanks and warm regards,*
*VIGNESH Mohan,*
*Research Scholar,*
*Delhi Technological University.*
*Delhi-110042.*

**Comment by tianshu129** [comment]
Thank you.



Tianshu
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/1/2023 14:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [tianshu129/foqat] Queries about the geom_psd function? (Issue #113) |

Actually I need to plot size distribution graphs in R studio. While I was
searching related to this I got your package. It is really a good package.
I would like to explore more about this package as of now I have explored
only a few functions.



*With thanks and warm regards,*
*VIGNESH Mohan,*
*Research Scholar,*
*Delhi Technological University.*
*Delhi-110042.*
